# Aca lo que hacemos es definir los 3 servicios que vamos a usar
# FRONTEND -> REACT
# BACKEND -> NODE/EXPRESS con PRISMA
# DB -> POSTGRES - SUPABASE

version: '3.8'

services:
  # Frontend React (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
      - ./frontend/.env
    environment:
      - PORT=5173
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true   # para hot reload estable en contenedor
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm start
    volumes:
      - ./frontend:/app          # hot reload del código
      - /app/node_modules        # evita pisar node_modules del contenedor
    networks:
      - app-network

  # Backend Node/Express (+ Prisma)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend/src/Imagenes:/imagenes:ro
    environment:
      - NODE_ENV=development
      - IMGS_DIR=/imagenes
    networks:
      - app-network

  # Base de Datos PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: app_db
    env_file:
      - ./backend/.env           # usa DATABASE_URL desde acá
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
